default:
	g++ -Wall -o bin/sniffer -I . -I ./include/elasticsearch -I ./include/rapidjson -I ./include/cpr ./include/elasticsearch/*.cpp ./include/cpr/*.cpp src/sniffer.cpp -lcurl -ltins -lpthread -std=c++11 
